schema_version: 1

context:
  version: "4.1.0"

package:
  name: pycantonese
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/p/pycantonese/pycantonese-${{ version }}.tar.gz
  sha256: f56cab5ac0b001ce95b614a9a5b6de75c35a1b625959c79195f64e257457e482

build:
  number: 0
  script:
    - cargo-bundle-licenses --format yaml --output ./THIRDPARTY.yml
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
    - ${{ stdlib('c') }}
  host:
    - python
    - pip
    - maturin >=1.0,<2.0
  run:
    - python
    - rustling >=0.6.0

tests:
  - python:
      imports:
        - pycantonese
      pip_check: true

about:
  summary: Cantonese Linguistics and NLP in Python
  license: MIT
  license_file:
    - LICENSE.txt
    - THIRDPARTY.yml
  homepage: https://pycantonese.org

extra:
  recipe-maintainers:
    - jacksonllee
